# Generated by Django 4.2.6 on 2023-10-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='conversation',
            new_name='item',
        ),
    ]
